#RewardMe by Joshscoper#
Configuration:
  prefix: "&6&lReward&eMe"

#Block types can be found at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#
BlockRewards:
  blocks:
    STONE:
      amount: 10
      cooldown: 10
      reward: "default_item"
    DIRT:
      amount: 10
      cooldown: 10
      reward: "default_money"
    OAK_LOGS:
      amount: 10
      cooldown: 10
      reward: "default_command"

#Mob types can be found at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html#
MobRewards:
  mobs:
    PIG:
      amount: 10
      cooldown: 10
      reward: "default_item"
    COW:
      amount: 10
      cooldown: 10
      reward: "default_money"
    SHEEP:
      amount: 10
      cooldown: 10
      reward: "default_command"